### ISSUE TITLE
Missing network passphrase in example compose file

### ISSUE THREAD

**Issue by todkap** [satoshipay/docker-stellar-horizon#12]
When trying to start docker compose, I was seeing the following in the logs...

> stellar-horizon-postgres_1  | 	    AS $_$ SELECT $1 $_$
> stellar-horizon_1           | 2019/04/26 11:09:11 Invalid config: network-passphrase is blank. Please specify --network-passphrase on the command line or set the NETWORK_PASSPHRASE environment variable.
> docker-stellar-horizon_stellar-horizon_1 exited with code 1
> 

If I add `- NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015` to the horizon ENV...

```
 stellar-horizon:
    image: satoshipay/stellar-horizon:0.17.2
    restart: on-failure
    ports:
    - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres@stellar-horizon-postgres/stellar-horizon?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://postgres@stellar-core-postgres/stellar-core?sslmode=disable
      - STELLAR_CORE_URL=http://stellar-core:11626
      - NETWORK_PASSPHRASE=Public Global Stellar Network ; September 2015
      - INGEST=true
```
and now I can access the server on http://localhost:8000/
